// <auto-generated />
using System;
using ArGeTesvikTool.DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArGeTesvikTool.DataAccess.Migrations
{
    [DbContext(typeof(AGMDbContext))]
    [Migration("20220218130207_new field added")]
    partial class newfieldadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessContactDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdentityNumber");

                    b.Property<string>("Mail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Mail");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NameSurname");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessContacts");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessFinancialInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AcquisitionTurnover")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AcquisitionTurnover");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("DomesticSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DomesticSales");

                    b.Property<decimal>("ExportSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ExportSales");

                    b.Property<decimal>("GrossSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GrossSales");

                    b.Property<decimal>("LongTermLoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongTermLoan");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<decimal>("NetSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NetSales");

                    b.Property<decimal>("RDExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RDExpenditure");

                    b.Property<decimal>("SortTermLoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SortTermLoan");

                    b.Property<decimal>("TotalAsset")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalAsset");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessFinancialInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ActivityCode");

                    b.Property<string>("Adress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Adress");

                    b.Property<decimal>("AvaibleCapital")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AvaibleCapital");

                    b.Property<string>("CRSNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CRSNumber");

                    b.Property<string>("ChamberCommerce")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ChamberCommerce");

                    b.Property<string>("CityCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CityCode");

                    b.Property<string>("CityText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CityText");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date");

                    b.Property<decimal>("FoundingCapital")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FoundingCapital");

                    b.Property<int>("IsSME")
                        .HasColumnType("int")
                        .HasColumnName("IsSME");

                    b.Property<string>("Mail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Mail");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Partner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Partner");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("PhoneNumber");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("date")
                        .HasColumnName("PublishDate");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("RegistrationNo");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TaxOffice");

                    b.Property<string>("TradeNumber")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("TradeNumber");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessIntroDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessIntros");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessSchemaDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("BusinessSchemas");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.GroupInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<DateTime>("FoundingDate")
                        .HasColumnType("date")
                        .HasColumnName("FoundingDate");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Origin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Origin");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessGroupInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.PersonnelDistributionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssociateDegree")
                        .HasColumnType("int")
                        .HasColumnName("AssociateDegree");

                    b.Property<int>("BachelorDegree")
                        .HasColumnType("int")
                        .HasColumnName("BachelorDegree");

                    b.Property<string>("CompanyUnit")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyUnit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<int>("Doctoral")
                        .HasColumnType("int")
                        .HasColumnName("Doctoral");

                    b.Property<int>("HighSchool")
                        .HasColumnType("int")
                        .HasColumnName("HighSchool");

                    b.Property<int>("MasterDegree")
                        .HasColumnType("int")
                        .HasColumnName("MasterDegree");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("PostDoctoral")
                        .HasColumnType("int")
                        .HasColumnName("PostDoctoral");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("Total");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("BusinessPersonnelDistributions");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.ShareholdersDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Origin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Origin");

                    b.Property<decimal>("Share")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Share");

                    b.Property<decimal>("ShareAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ShareAmount");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("BusinessShareholders");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.StrategyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessStrategies");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterAreaInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterAreaInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterContactDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("Birthday");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdentityNumber");

                    b.Property<string>("Mail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Mail");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NameSurname");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterContacts");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterFinancialInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AcquisitionTurnover")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AcquisitionTurnover");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("DomesticSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DomesticSales");

                    b.Property<decimal>("ExportSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ExportSales");

                    b.Property<decimal>("GrossSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GrossSales");

                    b.Property<decimal>("LongTermLoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongTermLoan");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<decimal>("NetSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NetSales");

                    b.Property<decimal>("RDExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RDExpenditure");

                    b.Property<decimal>("SortTermLoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SortTermLoan");

                    b.Property<decimal>("TotalAsset")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalAsset");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterFinancialInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("City");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Location");

                    b.Property<string>("Mail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Mail");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("OfficeArea")
                        .HasColumnType("int")
                        .HasColumnName("OfficeArea");

                    b.Property<int>("OtherArea")
                        .HasColumnType("int")
                        .HasColumnName("OtherArea");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("RegistrationNo");

                    b.Property<int>("TotalArea")
                        .HasColumnType("int")
                        .HasColumnName("TotalArea");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterSchemaDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterSchemas");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterPerformance.RdCenterPerformanceProjectDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<string>("CommercialProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CommercialProductName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Explanation");

                    b.Property<bool>("IsImportProduct")
                        .HasColumnType("bit")
                        .HasColumnName("IsImportProduct");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectName");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterPerformanceProjects");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterPerson.RdCenterPersonInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("EducationStatu")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EducationStatu");

                    b.Property<string>("GraduateUniversity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("GraduateUniversity");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdentityNumber");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NameSurname");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Location");

                    b.Property<string>("PersonPosition")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PersonPosition");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("RegistrationNo");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.Property<string>("UniversityDepartmant")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UniversityDepartmant");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterPersonInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterPerson.RdCenterPersonRewardDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterPersonRewars");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechAcademicLibraryDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterTechAcademicLibraries");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechAttendedEventDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AttendDate")
                        .HasColumnType("date")
                        .HasColumnName("AttendDate");

                    b.Property<string>("AttendedEvent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("AttendedEvent");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<int>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("Location");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("PersonNumber")
                        .HasColumnType("int")
                        .HasColumnName("PersonNumber");

                    b.Property<int>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("int")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechAttendedEvents");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechCollaborationDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Collaboration")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Collaboration");

                    b.Property<string>("CollaborationType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CollaborationType");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("CountryText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CountryText");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Partner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Partner");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechCollaborations");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechCompletedProjectDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("EquityAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EquityAmount");

                    b.Property<string>("InternationalProgName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("InternationalProgName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ProgramName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProgramName");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ProjectCode");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectName");

                    b.Property<decimal>("SupportAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SupportAmount");

                    b.Property<decimal>("TotalProjectBudget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalProjectBudget");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechCompletedProjects");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechIntellectualPropertyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("date")
                        .HasColumnName("ApplicationDate");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<int>("DevelopmentPlace")
                        .HasMaxLength(30)
                        .HasColumnType("int")
                        .HasColumnName("DevelopmentPlace");

                    b.Property<int>("International")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("International");

                    b.Property<string>("InventionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InventionType");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectName");

                    b.Property<int>("ProperyType")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("ProperyType");

                    b.Property<int>("Statu")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("Statu");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechIntellectualProperties");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechMentorInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("MentorFirmName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("MentorFirmName");

                    b.Property<string>("MentorOutput")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MentorOutput");

                    b.Property<string>("MentorSupport")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MentorSupport");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechMentorInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechOngoingProjectDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("EquityAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EquityAmount");

                    b.Property<string>("InternationalProgName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("InternationalProgName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ProgramName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProgramName");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ProjectCode");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectName");

                    b.Property<decimal>("SupportAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SupportAmount");

                    b.Property<decimal>("TotalProjectBudget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalProjectBudget");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechOngoingProjects");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechProjectManagementDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechProjectManagements");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechSoftwareDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CopyNumber")
                        .HasColumnType("int")
                        .HasColumnName("CopyNumber");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("SoftwareName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SoftwareName");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterTechSoftwares");
                });
#pragma warning restore 612, 618
        }
    }
}
