// <auto-generated />
using System;
using ArGeTesvikTool.DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArGeTesvikTool.DataAccess.Migrations
{
    [DbContext(typeof(AGMDbContext))]
    [Migration("20220126225958_BusinessDBCreate")]
    partial class BusinessDBCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ActivityCode");

                    b.Property<string>("Adress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Adress");

                    b.Property<decimal>("AvaibleCapital")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AvaibleCapital");

                    b.Property<int>("CRSNumber")
                        .HasColumnType("int")
                        .HasColumnName("CRSNumber");

                    b.Property<string>("ChamberCommerce")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ChamberCommerce");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("City");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<decimal>("FoundingCapital")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FoundingCapital");

                    b.Property<int>("IsSME")
                        .HasColumnType("int")
                        .HasColumnName("IsSME");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mail");

                    b.Property<string>("Partner")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Partner");

                    b.Property<int>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("PhoneNumber");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PublishDate");

                    b.Property<int>("RegistrationNo")
                        .HasColumnType("int");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TaxOffice");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.Property<int>("TradeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("TradeNumber");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessIntroDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Intro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BusinessIntros");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.GroupInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FoundingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.PersonnelDistributionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssociateDegree")
                        .HasColumnType("int");

                    b.Property<int>("BachelorDegree")
                        .HasColumnType("int");

                    b.Property<string>("CompanyUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Doctoral")
                        .HasColumnType("int");

                    b.Property<int>("HighSchool")
                        .HasColumnType("int");

                    b.Property<int>("MasterDegree")
                        .HasColumnType("int");

                    b.Property<int>("PostDoctoral")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonnelDistributions");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.ShareholdersDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Share")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShareAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Shareholders");
                });
#pragma warning restore 612, 618
        }
    }
}
