// <auto-generated />
using System;
using ArGeTesvikTool.DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArGeTesvikTool.DataAccess.Migrations
{
    [DbContext(typeof(AGMDbContext))]
    partial class AGMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessContactDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdentityNumber");

                    b.Property<string>("Mail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Mail");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("NameSurname")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NameSurname");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessContacts");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessFinancialInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AcquisitionTurnover")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AcquisitionTurnover");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("DomesticSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DomesticSales");

                    b.Property<decimal>("ExportSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ExportSales");

                    b.Property<decimal>("GrossSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GrossSales");

                    b.Property<decimal>("LongTermLoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongTermLoan");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<decimal>("NetSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NetSales");

                    b.Property<decimal>("RDExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RDExpenditure");

                    b.Property<decimal>("SortTermLoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SortTermLoan");

                    b.Property<decimal>("TotalAsset")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalAsset");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessFinancialInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ActivityCode");

                    b.Property<string>("Adress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Adress");

                    b.Property<decimal>("AvaibleCapital")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AvaibleCapital");

                    b.Property<string>("CRSNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CRSNumber");

                    b.Property<string>("ChamberCommerce")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ChamberCommerce");

                    b.Property<string>("CityCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CityCode");

                    b.Property<string>("CityText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CityText");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date");

                    b.Property<decimal>("FoundingCapital")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FoundingCapital");

                    b.Property<string>("IsSME")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("IsSME");

                    b.Property<string>("Mail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Mail");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Partner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Partner");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("PhoneNumber");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("date")
                        .HasColumnName("PublishDate");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("RegistrationNo");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TaxOffice");

                    b.Property<string>("TradeNumber")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("TradeNumber");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessIntroDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessIntros");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.BusinessSchemaDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("BusinessSchemas");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.GroupInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<DateTime>("FoundingDate")
                        .HasColumnType("date")
                        .HasColumnName("FoundingDate");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Origin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Origin");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessGroupInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.PersonnelDistributionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssociateDegree")
                        .HasColumnType("int")
                        .HasColumnName("AssociateDegree");

                    b.Property<int>("BachelorDegree")
                        .HasColumnType("int")
                        .HasColumnName("BachelorDegree");

                    b.Property<string>("CompanyUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CompanyUnit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<int>("Doctoral")
                        .HasColumnType("int")
                        .HasColumnName("Doctoral");

                    b.Property<int>("HighSchool")
                        .HasColumnType("int")
                        .HasColumnName("HighSchool");

                    b.Property<int>("MasterDegree")
                        .HasColumnType("int")
                        .HasColumnName("MasterDegree");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("PostDoctoral")
                        .HasColumnType("int")
                        .HasColumnName("PostDoctoral");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("Total");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("BusinessPersonnelDistributions");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.ShareholdersDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Origin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Origin");

                    b.Property<decimal>("Share")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Share");

                    b.Property<decimal>("ShareAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ShareAmount");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("BusinessShareholders");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Business.StrategyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("BusinessStrategies");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.FiscalYearDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("FiscalYears");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Index.NewDataDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("DomesticSalesRevenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DomesticSalesRevenue");

                    b.Property<int>("InternationalProjectNumber")
                        .HasColumnType("int")
                        .HasColumnName("InternationalProjectNumber");

                    b.Property<bool>("IsIso14001")
                        .HasColumnType("bit")
                        .HasColumnName("Iso14001");

                    b.Property<bool>("IsIso9001")
                        .HasColumnType("bit")
                        .HasColumnName("Iso9001");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("NationalProjectNumber")
                        .HasColumnType("int")
                        .HasColumnName("NationalProjectNumber");

                    b.Property<decimal>("OverseasSalesRevenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("OverseasSalesRevenue");

                    b.Property<decimal>("PeriodicExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PeriodicExpenditure");

                    b.Property<decimal>("ProjectPeriodicExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ProjectPeriodicExpenditure");

                    b.Property<decimal>("PublicPeriodicExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PublicPeriodicExpenditure");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("IndexNewDatas");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.Pacs.PersonelAttendanceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EventTime");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("PersonnelNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PersonnelNumber");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Surname");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int")
                        .HasColumnName("TerminalId");

                    b.Property<string>("TerminalName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TerminalName");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("PersonnelAttendances");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterAmountDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AnnualTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AnnualTotal");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("CustomTaxException")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CustomTaxException");

                    b.Property<decimal>("IncentiveAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("IncentiveAmount");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<decimal>("PremiumSupport")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PremiumSupport");

                    b.Property<decimal>("RatioTurnover")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RatioTurnover");

                    b.Property<decimal>("StampTaxException")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("StampTaxException");

                    b.Property<decimal>("TaxExemption")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TaxExemption");

                    b.Property<decimal>("TotalExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalExpenditure");

                    b.Property<decimal>("WithholdingIncentive")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("WithholdingIncentive");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterAmounts");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterAreaInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterAreaInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterContactDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("Birthday");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdentityNumber");

                    b.Property<string>("Mail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Mail");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("NameSurname")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NameSurname");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterContacts");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterDiscountDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CashSupport")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CashSupport");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("DepreciationAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DepreciationAmount");

                    b.Property<decimal>("DesignExpense")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DesignExpense");

                    b.Property<decimal>("ExternalBenefit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ExternalBenefit");

                    b.Property<decimal>("GeneralExpense")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GeneralExpense");

                    b.Property<decimal>("MaterialExpense")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MaterialExpense");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<decimal>("PersonelExpense")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PersonelExpense");

                    b.Property<decimal>("TaxExemption")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TaxExemption");

                    b.Property<decimal>("TaxFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TaxFee");

                    b.Property<decimal>("TotalExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalExpenditure");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterDiscounts");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterFinancialInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AcquisitionTurnover")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AcquisitionTurnover");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<decimal>("DomesticSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DomesticSales");

                    b.Property<decimal>("ExportSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ExportSales");

                    b.Property<decimal>("GrossSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GrossSales");

                    b.Property<decimal>("LongTermLoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LongTermLoan");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<decimal>("NetSales")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NetSales");

                    b.Property<decimal>("RDExpenditure")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RDExpenditure");

                    b.Property<decimal>("SortTermLoan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SortTermLoan");

                    b.Property<decimal>("TotalAsset")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalAsset");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterFinancialInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<string>("CityCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("CityCode");

                    b.Property<string>("CityText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CityText");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<DateTime>("DocReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Location");

                    b.Property<string>("Mail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Mail");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("OfficeArea")
                        .HasColumnType("int")
                        .HasColumnName("OfficeArea");

                    b.Property<int>("OtherArea")
                        .HasColumnType("int")
                        .HasColumnName("OtherArea");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("RegistrationNo");

                    b.Property<int>("TotalArea")
                        .HasColumnType("int")
                        .HasColumnName("TotalArea");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterPhysicalAreaDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterPhysicalAreas");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenter.RdCenterSchemaDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterSchemas");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterPerformance.RdCenterPerformanceProjectDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<string>("CommercialProductName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CommercialProductName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Explanation");

                    b.Property<bool>("IsImportProduct")
                        .HasColumnType("bit")
                        .HasColumnName("IsImportProduct");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectName");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterPerformanceProjects");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterPerson.RdCenterPersonInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("EducationStatu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("EducationStatu");

                    b.Property<string>("GraduateUniversity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("GraduateUniversity");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdentityNumber");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("NameSurname")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NameSurname");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Location");

                    b.Property<string>("PersonPosition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PersonPosition");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("RegistrationNo");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.Property<string>("UniversityDepartmant")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UniversityDepartmant");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterPersonInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterPerson.RdCenterPersonRewardDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterPersonRewars");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterPerson.RdCenterPersonTimeAwayDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityType")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("ActivityType");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdentityNumber");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Month")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("Month");

                    b.Property<decimal>("MonthlyTimeAway")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MonthlyTimeAway");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectCode");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterPersonTimeAways");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechAcademicLibraryDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterTechAcademicLibraries");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechAttendedEventDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AttendDate")
                        .HasColumnType("date")
                        .HasColumnName("AttendDate");

                    b.Property<string>("AttendedEvent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("AttendedEvent");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Location");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("PersonNumber")
                        .HasColumnType("int")
                        .HasColumnName("PersonNumber");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Text");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechAttendedEvents");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechCollaborationDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Collaboration")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Collaboration");

                    b.Property<string>("CollaborationType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CollaborationType");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("CountryCode");

                    b.Property<string>("CountryText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CountryText");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Partner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Partner");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechCollaborations");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechIntellectualPropertyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("date")
                        .HasColumnName("ApplicationDate");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("DevelopmentPlace")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DevelopmentPlace");

                    b.Property<string>("International")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("International");

                    b.Property<string>("InventionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InventionType");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectName");

                    b.Property<string>("ProperyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ProperyType");

                    b.Property<string>("Statu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Statu");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechIntellectualProperties");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechMentorInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("MentorFirmName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("MentorFirmName");

                    b.Property<string>("MentorOutput")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MentorOutput");

                    b.Property<string>("MentorSupport")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MentorSupport");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechMentorInfos");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechProjectDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<byte[]>("DocumentContent")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("DocumentContent");

                    b.Property<string>("DocumentContentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DocumentContentType");

                    b.Property<string>("DocumentFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DocumentFileName");

                    b.Property<decimal>("EquityAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EquityAmount");

                    b.Property<byte[]>("IncomeContent")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("IncomeContent");

                    b.Property<string>("IncomeContentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IncomeContentType");

                    b.Property<string>("IncomeFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IncomeFileName");

                    b.Property<decimal>("IntServiceProcurementAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("IntServiceProcurementAmount");

                    b.Property<string>("IntSupportProgram")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IntSupportProgram");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<decimal>("NatServiceProcurementAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NatServiceProcurementAmount");

                    b.Property<string>("NatSupportProgram")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NatSupportProgram");

                    b.Property<string>("OrderBase")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrderBase");

                    b.Property<int>("PersonNumber")
                        .HasColumnType("int")
                        .HasColumnName("PersonNumber");

                    b.Property<string>("ProjectActivity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectActivity");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ProjectCode");

                    b.Property<byte[]>("ProjectContent")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("ProjectContent");

                    b.Property<string>("ProjectContentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectContentType");

                    b.Property<decimal>("ProjectDuration")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ProjectDuration");

                    b.Property<DateTime>("ProjectEndDate")
                        .HasColumnType("date")
                        .HasColumnName("ProjectEndDate");

                    b.Property<string>("ProjectFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectFileName");

                    b.Property<string>("ProjectInnovative")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectInnovative");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ProjectName");

                    b.Property<string>("ProjectOutput")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectOutput");

                    b.Property<string>("ProjectRequirement")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectRequirement");

                    b.Property<DateTime>("ProjectStartDate")
                        .HasColumnType("date")
                        .HasColumnName("ProjectStartDate");

                    b.Property<string>("ProjectStatu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ProjectStatu");

                    b.Property<string>("ProjectSubject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectSubject");

                    b.Property<string>("ProjectSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectSummary");

                    b.Property<int>("ServiceProcurement")
                        .HasColumnType("int")
                        .HasColumnName("ServiceProcurement");

                    b.Property<decimal>("ServiceProcurementAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ServiceProcurementAmount");

                    b.Property<string>("ServiceProcurementSubject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServiceProcurementSubject");

                    b.Property<decimal>("SupportAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SupportAmount");

                    b.Property<decimal>("TotalProjectIncome")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalProjectIncome");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechProjects");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechProjectManagementDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileExtension");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FileName");

                    b.Property<string>("ModifedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("RdCenterTechProjectManagements");
                });

            modelBuilder.Entity("ArGeTesvikTool.Entities.Concrete.RdCenterTech.RdCenterTechSoftwareDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CopyNumber")
                        .HasColumnType("int")
                        .HasColumnName("CopyNumber");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedUserName");

                    b.Property<string>("ModifedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModifedUserName");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("SoftwareName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SoftwareName");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("RdCenterTechSoftwares");
                });
#pragma warning restore 612, 618
        }
    }
}
